# Generated by Django 3.2.25 on 2024-06-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(editable=False, max_length=31)),
                ('title', models.CharField(max_length=64)),
                ('danceability', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('key', models.IntegerField(null=True)),
                ('loudness', models.FloatField(null=True)),
                ('mode', models.IntegerField(null=True)),
                ('acousticness', models.FloatField(null=True)),
                ('instrumentalness', models.FloatField(null=True)),
                ('liveness', models.FloatField(null=True)),
                ('valence', models.FloatField(null=True)),
                ('tempo', models.FloatField(null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('time_signature', models.IntegerField(null=True)),
                ('num_bars', models.IntegerField(null=True)),
                ('num_sections', models.IntegerField(null=True)),
                ('num_segments', models.IntegerField(null=True)),
                ('song_class', models.IntegerField(null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
